version: "3.9"

networks:
  dev:
    driver: bridge
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - auth_db
    networks:
      - dev
    
  auth_db:
    image: postgres:15
    environment:
      POSTGRES_DB: "auth_DB"
      POSTGRES_USER: "amogus"
      POSTGRES_PASSWORD: "1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - auth_data:/var/lib/postgresql/data/pgdata
    ports:
      - "2751:5432"
    networks:
      - dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U amogus -d auth_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - auth_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - dev

  auth:
    build:
       context: ./auth_server
       dockerfile: Dockerfile
    container_name: server-auth
    hostname: server-auth
    ports:
       - "8080:8080"
    networks:
       - dev
  redis:
    image: redis:7-alpine
    container_name: redis-container
    ports:
      - "6379:6379" # Проброс порта
    volumes:
      - redis-data:/data # Для сохранения данных
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "debug" ]
    restart: unless-stopped
    networks:
      - dev
  
  liquibase-migrations:
      container_name: migrations_fastbuy
      image: liquibase/liquibase:4.29
      depends_on:
        - auth_db
      command:
        - --searchPath=/changesets
        - --changelog-file=master.yaml
        - --driver=org.postgresql.Driver
        - --url=jdbc:postgresql://auth_db:5432/auth_DB
        - --username=amogus
        - --password=1234
        - update
      volumes:
        - ./db/init.sql:/changesets/init.sql
        - ./db/master.yaml:/changesets/master.yaml
      networks:
        - dev

volumes:
  auth_data:
  redis-data:
  pgadmin_data:

